# Generated by Django 5.2.5 on 2025-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, help_text='e.g. Grade 8 student or participant', max_length=190)),
                ('feedback', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
